python evaluate_gpt2.py --input_file="../data/not/complete_1-box-0-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_1-box-1-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_1-box-2-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_1-box-3-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_1-box-4-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_1-box-5-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"

python evaluate_gpt2.py --input_file="../data/not/complete_3-box-0-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_3-box-1-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_3-box-2-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_3-box-3-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_3-box-4-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_3-box-5-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"

python evaluate_gpt2.py --input_file="../data/not/complete_5-box-0-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_5-box-1-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_5-box-2-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_5-box-3-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_5-box-4-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
python evaluate_gpt2.py --input_file="../data/not/complete_5-box-5-op.jsonl" --model_name="gpt2" --type="explicit" --few_shot --few_shot_type="single"
