python evaluate.py --input_file="../data/conversational/complete_1-box-0-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_1-box-1-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_1-box-2-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_1-box-3-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_1-box-4-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_1-box-5-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"

python evaluate.py --input_file="../data/conversational/complete_3-box-0-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_3-box-1-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_3-box-2-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_3-box-3-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_3-box-4-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_3-box-5-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"

python evaluate.py --input_file="../data/conversational/complete_5-box-0-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_5-box-1-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_5-box-2-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_5-box-3-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_5-box-4-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"
python evaluate.py --input_file="../data/conversational/complete_5-box-5-op.jsonl" --model_name="t5-base" --type="implicit" --few_shot --few_shot_type="compact"