# t5-base

python evaluate.py --input_file="../data/conversational/complete_1-box-0-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-1-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-2-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-3-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-4-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-5-op.jsonl" --model_name="t5-base" --type="implicit"

python evaluate.py --input_file="../data/conversational/complete_3-box-0-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-1-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-2-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-3-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-4-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-5-op.jsonl" --model_name="t5-base" --type="implicit"

python evaluate.py --input_file="../data/conversational/complete_1-box-0-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-1-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-2-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-3-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-4-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-5-op.jsonl" --model_name="t5-base" --type="explicit"

python evaluate.py --input_file="../data/conversational/complete_3-box-0-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-1-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-2-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-3-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-4-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-5-op.jsonl" --model_name="t5-base" --type="explicit"

python evaluate.py --input_file="../data/not/complete_1-box-0-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-1-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-2-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-3-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-4-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-5-op.jsonl" --model_name="t5-base" --type="implicit"

python evaluate.py --input_file="../data/not/complete_3-box-0-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-1-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-2-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-3-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-4-op.jsonl" --model_name="t5-base" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-5-op.jsonl" --model_name="t5-base" --type="implicit"

python evaluate.py --input_file="../data/not/complete_1-box-0-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-1-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-2-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-3-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-4-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-5-op.jsonl" --model_name="t5-base" --type="explicit"

python evaluate.py --input_file="../data/not/complete_3-box-0-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-1-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-2-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-3-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-4-op.jsonl" --model_name="t5-base" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-5-op.jsonl" --model_name="t5-base" --type="explicit"

# gpt2

python evaluate.py --input_file="../data/conversational/complete_1-box-0-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-1-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-2-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-3-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-4-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-5-op.jsonl" --model_name="gtp2" --type="implicit"

python evaluate.py --input_file="../data/conversational/complete_3-box-0-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-1-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-2-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-3-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-4-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-5-op.jsonl" --model_name="gtp2" --type="implicit"

python evaluate.py --input_file="../data/conversational/complete_1-box-0-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-1-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-2-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-3-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-4-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_1-box-5-op.jsonl" --model_name="gtp2" --type="explicit"

python evaluate.py --input_file="../data/conversational/complete_3-box-0-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-1-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-2-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-3-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-4-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/conversational/complete_3-box-5-op.jsonl" --model_name="gtp2" --type="explicit"

python evaluate.py --input_file="../data/not/complete_1-box-0-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-1-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-2-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-3-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-4-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_1-box-5-op.jsonl" --model_name="gtp2" --type="implicit"

python evaluate.py --input_file="../data/not/complete_3-box-0-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-1-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-2-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-3-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-4-op.jsonl" --model_name="gtp2" --type="implicit"
python evaluate.py --input_file="../data/not/complete_3-box-5-op.jsonl" --model_name="gtp2" --type="implicit"

python evaluate.py --input_file="../data/not/complete_1-box-0-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-1-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-2-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-3-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-4-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_1-box-5-op.jsonl" --model_name="gtp2" --type="explicit"

python evaluate.py --input_file="../data/not/complete_3-box-0-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-1-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-2-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-3-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-4-op.jsonl" --model_name="gtp2" --type="explicit"
python evaluate.py --input_file="../data/not/complete_3-box-5-op.jsonl" --model_name="gtp2" --type="explicit"